metadatablock.name=socialscience
metadatablock.displayName=Social Science and Humanities Metadata
metadatablock.displayFacet=Social Science and Humanities
datasetfieldtype.unitOfAnalysis.title=Unit of Analysis
datasetfieldtype.universe.title=Universe
datasetfieldtype.timeMethod.title=Time Method
datasetfieldtype.dataCollector.title=Data Collector
datasetfieldtype.collectorTraining.title=Collector Training
datasetfieldtype.frequencyOfDataCollection.title=Frequency
datasetfieldtype.samplingProcedure.title=Sampling Procedure
datasetfieldtype.targetSampleSize.title=Target Sample Size
datasetfieldtype.targetSampleActualSize.title=Actual
datasetfieldtype.targetSampleSizeFormula.title=Formula
datasetfieldtype.deviationsFromSampleDesign.title=Major Deviations for Sample Design
datasetfieldtype.collectionMode.title=Collection Mode
datasetfieldtype.researchInstrument.title=Type of Research Instrument
datasetfieldtype.dataCollectionSituation.title=Characteristics of Data Collection Situation
datasetfieldtype.actionsToMinimizeLoss.title=Actions to Minimize Losses
datasetfieldtype.controlOperations.title=Control Operations
datasetfieldtype.weighting.title=Weighting
datasetfieldtype.cleaningOperations.title=Cleaning Operations
datasetfieldtype.datasetLevelErrorNotes.title=Study Level Error Notes
datasetfieldtype.responseRate.title=Response Rate
datasetfieldtype.samplingErrorEstimates.title=Estimates of Sampling Error
datasetfieldtype.otherDataAppraisal.title=Other Forms of Data Appraisal
datasetfieldtype.socialScienceNotes.title=Notes
datasetfieldtype.socialScienceNotesType.title=Type
datasetfieldtype.socialScienceNotesSubject.title=Subject
datasetfieldtype.socialScienceNotesText.title=Text
datasetfieldtype.unitOfAnalysis.description=Describes the entity being analyzed in the study or variable; e.g individual, family, households etc.; controlled vocabulary https://vocabularies.cessda.eu/vocabulary/AnalysisUnit
datasetfieldtype.universe.description=Freetext description of the population covered by the data in the file; the group of people or other elements that are the object of the study and to which the study results refer
datasetfieldtype.timeMethod.description=Describes the time dimension of the data collection; e.g longitudinal, time series, cross-section etc.; controlled vocabulary https://vocabularies.cessda.eu/vocabulary/TimeMethod
datasetfieldtype.dataCollector.description=Individual, agency or organization responsible for  administering the questionnaire or interview or compiling the data.
datasetfieldtype.collectorTraining.description=Type of training provided to the data collector
datasetfieldtype.frequencyOfDataCollection.description=If the data collected includes more than one point in time, indicate the frequency with which the data was collected; that is, monthly, quarterly, or other.
datasetfieldtype.samplingProcedure.description=Type of sampling procedure used for data collection; e.g. total universe/complete enumeration, probability: simple random, non-probability: availability etc.; controlled vocabulary https://vocabularies.cessda.eu/vocabulary/SamplingProcedure
datasetfieldtype.targetSampleSize.description=Specific information regarding the target sample size, actual  sample size, and the formula used to determine this.
datasetfieldtype.targetSampleActualSize.description=Actual sample size.
datasetfieldtype.targetSampleSizeFormula.description=Formula used to determine target sample size.
datasetfieldtype.deviationsFromSampleDesign.description=Show correspondence as well as discrepancies between the sampled units (obtained) and available statistics for the population (age, sex-ratio, marital status, etc.) as a whole.
datasetfieldtype.collectionMode.description=The procedure, technique, or mode of inquiry used to attain the data; e.g. face-to-face interview, self-administered questionnaire, field observation etc.; controlled vocabulary https://vocabularies.cessda.eu/vocabulary/ModeOfCollection
datasetfieldtype.researchInstrument.description=Type of the data collection instrument; e.g. questionnaire, data collection guidelines, programming script etc.; controlled vocabulary https://vocabularies.cessda.eu/vocabulary/TypeOfInstrument
datasetfieldtype.dataCollectionSituation.description=Description of noteworthy aspects of the data collection situation. Includes information on factors such as cooperativeness of respondents, duration of interviews, number of call backs, or similar.
datasetfieldtype.actionsToMinimizeLoss.description=Summary of actions taken to minimize data loss. Include information on actions such as follow-up visits, supervisory checks, historical matching, estimation, and so on.
datasetfieldtype.controlOperations.description=Control OperationsMethods to facilitate data control performed by the primary investigator or by the data archive.
datasetfieldtype.weighting.description=The use of sampling procedures might make it necessary to apply weights to produce accurate statistical results. Describes the criteria for using weights in analysis of a collection. If a weighting formula or coefficient was developed, the formula is provided, its elements are defined, and it is indicated how the formula was applied to the data.
datasetfieldtype.cleaningOperations.description=Methods used to clean the data collection, such as consistency checking, wildcode checking, or other.
datasetfieldtype.datasetLevelErrorNotes.description=Note element used for any information annotating or clarifying the methodology and processing of the study.
datasetfieldtype.responseRate.description=Percentage of sample members who provided information.
datasetfieldtype.samplingErrorEstimates.description=Measure of how precisely one can estimate a population value from a given sample.
datasetfieldtype.otherDataAppraisal.description=Other issues pertaining to the data appraisal. Describe issues such as response variance, nonresponse rate  and testing for bias, interviewer and response bias, confidence levels, question bias, or similar.
datasetfieldtype.socialScienceNotes.description=General notes about this Dataset.
datasetfieldtype.socialScienceNotesType.description=Type of note.
datasetfieldtype.socialScienceNotesSubject.description=Note subject.
datasetfieldtype.socialScienceNotesText.description=Text for this note.
datasetfieldtype.unitOfAnalysis.watermark=
datasetfieldtype.universe.watermark=
datasetfieldtype.timeMethod.watermark=
datasetfieldtype.dataCollector.watermark=FamilyName, GivenName or Organization
datasetfieldtype.collectorTraining.watermark=
datasetfieldtype.frequencyOfDataCollection.watermark=
datasetfieldtype.samplingProcedure.watermark=
datasetfieldtype.targetSampleSize.watermark=
datasetfieldtype.targetSampleActualSize.watermark=Enter an integer...
datasetfieldtype.targetSampleSizeFormula.watermark=
datasetfieldtype.deviationsFromSampleDesign.watermark=
datasetfieldtype.collectionMode.watermark=
datasetfieldtype.researchInstrument.watermark=
datasetfieldtype.dataCollectionSituation.watermark=
datasetfieldtype.actionsToMinimizeLoss.watermark=
datasetfieldtype.controlOperations.watermark=
datasetfieldtype.weighting.watermark=
datasetfieldtype.cleaningOperations.watermark=
datasetfieldtype.datasetLevelErrorNotes.watermark=
datasetfieldtype.responseRate.watermark=
datasetfieldtype.samplingErrorEstimates.watermark=
datasetfieldtype.otherDataAppraisal.watermark=
datasetfieldtype.socialScienceNotes.watermark=
datasetfieldtype.socialScienceNotesType.watermark=
datasetfieldtype.socialScienceNotesSubject.watermark=
datasetfieldtype.socialScienceNotesText.watermark=